### ISSUE TITLE
提示语法错误

### ISSUE THREAD

**Issue by Mrx1e** [zaxtyson/LanZouCloud-API#24]
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/脚本/lanzhou_api.py", line 3, in <module>
    from lanzou.api import LanZouCloud
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\lanzou\api\__init__.py", line 1, in <module>
    from lanzou.api.core import LanZouCloud
  File "<fstring>", line 1
    (parent_id=)
              ^
SyntaxError: invalid syntax

纯小白，在get_cookie时报语法错误，代码如下
# -*- coding: utf-8 -*-
__author__ = 'Administrator'
from lanzou.api import LanZouCloud
lzy=LanZouCloud()
cookie=lzy.get_cookie()
print(cookie)

**Comment by zaxtyson** [comment]
因为使用了 Python3.8 的特性(代码写起来方便)，所以低版本会爆语法错误：https://github.com/zaxtyson/LanZouCloud-CMD/issues/38#issuecomment-610734709

使用Python3.8+运行或者fork代码，再稍加修改~~

**Comment by zaxtyson** [comment]
还有就是，需要登录后才能调用 `get_cookie()`，这是以前使用用户名密码登录的时候，用来获取用户 cookie 的，之后官方给网页版、app端全部加了验证，现在只能用cookie登录了，参见：https://github.com/zaxtyson/LanZouCloud-API/issues/21#issuecomment-632964409
