### ISSUE TITLE
python3.6 导入api异常

### ISSUE THREAD

**Issue by lihuacai168** [zaxtyson/LanZouCloud-API#9]
# api版本-2.4.0.1
```
[root@ixxxxxx ~]# pip install lanzou-api
Looking in indexes: https://pypi.doubanio.com/simple/
Collecting lanzou-api
  Downloading https://pypi.doubanio.com/packages/fa/9a/574e9c19b51bd19765ca5127c7f5cd0354a9af24199481c1a6c1af373a27/lanzou_api-2.4.0.1-py3-none-any.whl
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from lanzou-api) (2.20.1)
Requirement already satisfied: requests-toolbelt in /usr/local/lib/python3.6/site-packages (from lanzou-api) (0.8.0)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->lanzou-api) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->lanzou-api) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->lanzou-api) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->lanzou-api) (3.0.4)
Installing collected packages: lanzou-api
Successfully installed lanzou-api-2.4.0.1
You are using pip version 18.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
# centos7的python3.6.8版本
```
[root@ixxxxxx ~]# python3.6
Python 3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.

```
# 异常报错
```
>>> from lanzhou import api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'lanzhou'
>>> from lanzou import api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/lanzou/api/__init__.py", line 1, in <module>
    from lanzou.api.core import LanZouCloud
  File "<fstring>", line 1
    (parent_id=)
              ^
SyntaxError: invalid syntax
```

**Comment by zaxtyson** [comment]
python 3.6 在 循环导入有一个 bug ，在3.7修复了，见：https://bugs.python.org/issue30024
建议使用新版本的 3.8，但是千万不要卸载系统自带的 python
之后 `python3.8 -m pip install lanzou-api`
因为手边没有 Centos，我试了虚拟机里面的 Ubuntu Server，3.6.8的确是有问题，但是服务器上面用 3.6.9就没有问题，还是用最新版吧
